### ISSUE TITLE
Translation of tags and category descriptions 

### ISSUE THREAD

**Issue by dadex78** [paviliondev/discourse-multilingual#46]
Is the current version of the plugin supposed to translate categories/category descriptions/subcategories/tags? or is any of these elements not managed and will be handled in future versions?

**Comment by merefield** [comment]
That functionality is supported

We've just merged several PRs which should make the experience much better.  The final one should fix most things.

**Comment by merefield** [comment]
The description translation only occurs on the category page display, not within the about topic.

guide here: https://thepavilion.io/t/adding-translations/2552?u=merefield

**Comment by dadex78** [comment]
We tried but we still cannot get the descriptions translated in the categories page.

Desktop category page style = Boxes with subcategories
Any suggestion is welcome, please let us know if you need any further information

![image](https://user-images.githubusercontent.com/108268061/178964925-5529b118-be6b-43a2-b71d-2c2b51b218f1.png)

**Comment by merefield** [comment]
That’s working for me.  What does your `category_description.***.yml` look like?

Have you updated to latest?

**Comment by dadex78** [comment]
May you please share a category_description.***.yml sample?
We'll double check if we are making any mistake

**Comment by merefield** [comment]
It’s the same as for name except for the slightly different file name.  Make sure the description is in quotes.

**Comment by merefield** [comment]
That's great news, thanks for confirming.  I'll close this for time being.
